name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk-version: [ 11 ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java ${{ matrix.jdk-version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.jdk-version }}
          cache: 'maven'
          
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-          

      - name: Build with Maven
        run: ./mvnw -T 4 --batch-mode --update-snapshots -Dmaven.test.skip=true package
        
      - name: Set Env
        run: |
          echo "CommitId=`sh dev/commitId.sh`" >> $GITHUB_ENV
          
      - name: Get Env
        run: echo ${{ env.CommitId }}
        
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk-version: [ 11 ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java ${{ matrix.jdk-version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.jdk-version }}
          cache: 'maven'
          
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-    

      - name: Checking Code Style
        run: ./mvnw spotless:check            
        
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk-version: [ 11 ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java ${{ matrix.jdk-version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.jdk-version }}
          cache: 'maven'

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-           

      - name: Test
        run: ./mvnw -T 4 --batch-mode -Dmaven.test.jvmargs='--add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-exports java.base/sun.nio.ch=ALL-UNNAMED --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens=java.base/jdk.internal.misc=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED' test
        
      - name: Report
        run: ./mvnw -T 4 --batch-mode -Dmaven.test.jvmargs='--add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-exports java.base/sun.nio.ch=ALL-UNNAMED --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens=java.base/jdk.internal.misc=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED' jacoco:report        

      - name: Upload test coverage report
        run: bash <(curl -s https://codecov.io/bash)  -f '**/jacoco.xml'       
  
  ci:
    runs-on: ubuntu-latest
    needs: [ build, lint, test]
    steps:
      - name: Aggregate outcomes
        run: echo "build succeeded"

