name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Checking Code Style
        run: ./mvnw spotless:check

      - name: Build with Maven
        run: ./mvnw -T 4 --batch-mode --update-snapshots -Dmaven.test.skip=true package
  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      # because there are some error tests      
      - name: Test
        run: ./mvnw test -Dmaven.test.failure.ignore=true

      - name: Upload test coverage report
        run: bash <(curl -s https://codecov.io/bash)
  
  
  ci:
    runs-on: ubuntu-latest
    needs: [ build, test ]
    steps:
      - name: Aggregate outcomes
        run: echo "build succeeded"        
