name: Docker

on:
  workflow_dispatch:
    inputs:
      release_image_version:
        description: 'Release Docker Image'
        default: 'X.X.X'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk-version: [ 11, 17, 21 ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java ${{ matrix.jdk-version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.jdk-version }}
          cache: 'maven'

      - name: Docker Build
        run: bash deploy.sh ${{ github.event.inputs.release_image_version }}
        working-directory: ./docker

  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk-version: [ 11, 17, 21 ]
    needs: [ build ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java ${{ matrix.jdk-version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.jdk-version }}
          cache: 'maven'

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Push
        run: docker image push ${{ secrets.DOCKERHUB_USERNAME }}/bitlap:${{ github.event.inputs.release_image_version }}
  
  ci:
    runs-on: ubuntu-latest
    needs: [ build, publish ]
    steps:
      - name: Aggregate outcomes
        run: echo "build succeeded"        
